package studio.agent.platform.internalapi;

import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.http.CacheControl;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;
import studio.agent.platform.security.SecretBox;
import studio.agent.platform.security.WorkerTokenGuard;
import studio.agent.platform.storage.ObjectStoreService;

/** Credentials are exposed only here, after an owner-scoped task join and worker-token check. */
@RestController
@RequestMapping("/internal")
public class InternalWorkerController {
  private final JdbcClient jdbc; private final WorkerTokenGuard tokens; private final SecretBox secrets; private final ObjectStoreService objects;
  public InternalWorkerController(JdbcClient jdbc,WorkerTokenGuard tokens,SecretBox secrets,ObjectStoreService objects){this.jdbc=jdbc;this.tokens=tokens;this.secrets=secrets;this.objects=objects;}
  @GetMapping("/worker-context/agent/{taskId}") ResponseEntity<Map<String,Object>> agent(@PathVariable UUID taskId){var row=task(taskId);var profiles=jdbc.sql("SELECT id,reference,name FROM login_profiles WHERE owner_id=:owner ORDER BY reference").param("owner",row.owner()).query((rs,n)->Map.<String,Object>of("id",rs.getObject(1,UUID.class),"reference",rs.getString(2),"name",rs.getString(3))).list();return noStore(Map.of("taskId",taskId,"sourceUrl",objects.presignGet(row.sourceKey(),Duration.ofMinutes(10)).toString(),"template",Map.of("id",row.templateId(),"format",row.format(),"markdown",nullToEmpty(row.markdown()),"html",nullToEmpty(row.html()),"css",nullToEmpty(row.css()),"schema",row.schema()),"parameters",row.parameters(),"providerProfileId",row.providerId(),"modelId",row.modelId(),"loginProfiles",profiles));}
  @GetMapping("/worker-context/browser/{taskId}") ResponseEntity<Map<String,Object>> browser(@RequestHeader("Authorization") String auth,@PathVariable UUID taskId){tokens.requireBrowser(auth);var row=task(taskId);var profiles=jdbc.sql("SELECT id,reference,name,login_url,login_path FROM login_profiles WHERE owner_id=:owner ORDER BY reference").param("owner",row.owner()).query((rs,n)->Map.<String,Object>of("id",rs.getObject(1,UUID.class),"reference",rs.getString(2),"name",rs.getString(3),"loginUrl",rs.getString(4),"loginPath",nullToEmpty(rs.getString(5)))).list();return noStore(Map.of("taskId",taskId,"baseUrl",row.baseUrl(),"allowedOrigins",List.of(origin(row.baseUrl())),"placeholderManifest",List.of(),"loginProfiles",profiles));}
  @PostMapping("/tasks/{taskId}/provider-credential") ResponseEntity<Map<String,Object>> provider(@RequestHeader("Authorization") String auth,@PathVariable UUID taskId){tokens.requireAgent(auth);var row=jdbc.sql("SELECT t.owner_id,p.id,p.base_url,p.encrypted_api_key,p.options::text,t.model_id FROM tasks t JOIN provider_profiles p ON p.id=t.provider_profile_id WHERE t.id=:task AND t.owner_id=p.owner_id").param("task",taskId).query((rs,n)->new Provider(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6))).optional().orElseThrow(()->new IllegalArgumentException("task provider not found"));return noStore(Map.of("providerProfileId",row.id(),"endpoint",row.endpoint(),"model",row.model(),"apiKey",secrets.decrypt(row.owner().toString(),row.key()),"options",row.options()));}
  @PostMapping("/tasks/{taskId}/login-profiles/{profileId}/credential") ResponseEntity<Map<String,Object>> login(@RequestHeader("Authorization") String auth,@PathVariable UUID taskId,@PathVariable UUID profileId){tokens.requireBrowser(auth);var row=jdbc.sql("SELECT p.owner_id,p.reference,p.login_url,p.login_path,p.username_locator::text,p.password_locator::text,p.submit_locator::text,p.encrypted_username,p.encrypted_password FROM tasks t JOIN login_profiles p ON p.owner_id=t.owner_id WHERE t.id=:task AND p.id=:profile").param("task",taskId).param("profile",profileId).query((rs,n)->new Login(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9))).optional().orElseThrow(()->new IllegalArgumentException("login profile not found"));return noStore(Map.of("reference",row.ref(),"loginUrl",row.url(),"loginPath",nullToEmpty(row.path()),"usernameLocator",jsonObject(row.userLocator()),"passwordLocator",jsonObject(row.passwordLocator()),"submitLocator",jsonObject(row.submitLocator()),"username",secrets.decrypt(row.owner().toString(),row.username()),"password",secrets.decrypt(row.owner().toString(),row.password())));}
  record PresignRequest(String name,String kind,String mediaType,long sizeBytes,String sha256) {}
  @PostMapping("/tasks/{taskId}/artifacts/presign") @org.springframework.transaction.annotation.Transactional ResponseEntity<Map<String,Object>> presign(@PathVariable UUID taskId,@RequestBody PresignRequest request){task(taskId);if(request.name()==null||request.name().isBlank()||request.mediaType()==null||request.mediaType().isBlank()||request.sizeBytes()<0||request.sha256()==null||!request.sha256().matches("[0-9a-fA-F]{64}"))throw new IllegalArgumentException("invalid artifact reservation");var artifact=UUID.randomUUID();var reservation=UUID.randomUUID();var key="artifacts/"+taskId+"/"+artifact+"/1";var now=java.time.OffsetDateTime.now();jdbc.sql("INSERT INTO artifacts(id,task_id,name,kind,current_version,created_at) VALUES(:id,:task,:name,:kind,0,:now)").param("id",artifact).param("task",taskId).param("name",request.name()).param("kind",request.kind()==null?"FILE":request.kind()).param("now",now).update();jdbc.sql("INSERT INTO object_reservations(id,task_id,artifact_id,object_key,media_type,expected_size,expected_sha256,expires_at) VALUES(:id,:task,:artifact,:key,:media,:size,:sha,:expires)").param("id",reservation).param("task",taskId).param("artifact",artifact).param("key",key).param("media",request.mediaType()).param("size",request.sizeBytes()).param("sha",request.sha256().toLowerCase()).param("expires",now.plusMinutes(10)).update();return noStore(Map.of("artifactId",artifact,"reservationId",reservation,"putUrl",objects.presignPut(key,request.mediaType(),request.sizeBytes(),request.sha256(),Duration.ofMinutes(10)).toString()));}
  @PostMapping("/tasks/{taskId}/artifacts/{artifactId}/complete") @org.springframework.transaction.annotation.Transactional ResponseEntity<Map<String,Object>> complete(@RequestHeader("Authorization") String auth,@PathVariable UUID taskId,@PathVariable UUID artifactId,@RequestBody Map<String,String> request){tokens.requireBrowser(auth);var reservation=jdbc.sql("SELECT id,object_key,media_type,expected_size,expected_sha256 FROM object_reservations WHERE task_id=:task AND artifact_id=:artifact AND completed_at IS NULL AND expires_at>:now FOR UPDATE").param("task",taskId).param("artifact",artifactId).param("now",java.time.OffsetDateTime.now()).query((rs,n)->new Reservation(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getLong(4),rs.getString(5))).optional().orElseThrow(()->new IllegalArgumentException("artifact reservation not found"));var head=objects.head(reservation.key());var actual=java.util.Base64.getEncoder().encodeToString(java.util.HexFormat.of().parseHex(reservation.sha()));if(head.size()!=reservation.size()||!actual.equals(head.checksumSha256()))throw new IllegalArgumentException("artifact checksum or size mismatch");jdbc.sql("INSERT INTO artifact_versions(id,artifact_id,ordinal,object_key,media_type,size_bytes,sha256,manifest,verification_report,created_at) VALUES(:id,:artifact,1,:key,:media,:size,:sha,CAST(:manifest AS jsonb),'{}'::jsonb,:now)").param("id",UUID.randomUUID()).param("artifact",artifactId).param("key",reservation.key()).param("media",reservation.media()).param("size",reservation.size()).param("sha",reservation.sha()).param("manifest",request.getOrDefault("manifest","{}")).param("now",java.time.OffsetDateTime.now()).update();jdbc.sql("UPDATE artifacts SET current_version=1 WHERE id=:id").param("id",artifactId).update();jdbc.sql("UPDATE object_reservations SET completed_at=:now WHERE id=:id").param("now",java.time.OffsetDateTime.now()).param("id",reservation.id()).update();return noStore(Map.of("artifactId",artifactId,"completed",true));}
  private Task task(UUID id){return jdbc.sql("SELECT t.owner_id,r.object_key,t.template_version_id,v.output_format,v.markdown_template,v.html_template,v.css,v.parameter_schema::text,t.parameters::text,t.provider_profile_id,t.model_id,COALESCE((SELECT login_url FROM login_profiles l WHERE l.owner_id=t.owner_id ORDER BY created_at LIMIT 1),'') FROM tasks t JOIN project_revisions r ON r.id=t.project_revision_id JOIN template_versions v ON v.id=t.template_version_id WHERE t.id=:id").param("id",id).query((rs,n)->new Task(rs.getObject(1,UUID.class),rs.getString(2),rs.getObject(3,UUID.class),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getObject(10,UUID.class),rs.getString(11),rs.getString(12))).optional().orElseThrow(()->new IllegalArgumentException("task not found"));}
  private static ResponseEntity<Map<String,Object>> noStore(Map<String,Object> body){return ResponseEntity.ok().cacheControl(CacheControl.noStore()).header("Pragma","no-cache").body(body);}
  private static String nullToEmpty(String v){return v==null?"":v;} private static String origin(String url){try{var u=java.net.URI.create(url);return u.getScheme()+"://"+u.getAuthority();}catch(Exception e){return url;}}
  private static Object jsonObject(String value){try{return new tools.jackson.databind.ObjectMapper().readValue(value,Object.class);}catch(tools.jackson.core.JacksonException e){throw new IllegalStateException("stored locator is invalid",e);}}
  private record Task(UUID owner,String sourceKey,UUID templateId,String format,String markdown,String html,String css,String schema,String parameters,UUID providerId,String modelId,String baseUrl){} private record Provider(UUID owner,UUID id,String endpoint,String key,String options,String model){} private record Login(UUID owner,String ref,String url,String path,String userLocator,String passwordLocator,String submitLocator,String username,String password){} private record Reservation(UUID id,String key,String media,long size,String sha){}
}
