package studio.agent.platform.task;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
import studio.agent.contracts.CreateTaskRequest;
import studio.agent.contracts.TaskStatus;
import studio.agent.platform.security.CurrentUser;
import studio.agent.platform.workflow.TaskWorkflowDispatchService;

@RestController
@RequestMapping({"/v1/tasks", "/api/v1/tasks"})
public class TaskController {
  private final JdbcClient jdbc;
  private final TaskWorkflowDispatchService workflows;
  public TaskController(JdbcClient jdbc, TaskWorkflowDispatchService workflows){this.jdbc=jdbc;this.workflows=workflows;}
  record View(UUID taskId,UUID projectId,String type,String status,OffsetDateTime createdAt,OffsetDateTime updatedAt,String resultReference,String failureCode) {}
  record ApprovalInput(String kind,String prompt,List<String> choices,OffsetDateTime expiresAt) {}
  record DecisionInput(String decision,String text,String approvedReference) {}

  @PostMapping @ResponseStatus(HttpStatus.ACCEPTED) @org.springframework.transaction.annotation.Transactional
  View create(CurrentUser user,@RequestHeader("Idempotency-Key") String key,@RequestBody CreateTaskRequest request){
    key = normalizeIdempotencyKey(key);
    if(!ownsProject(user,request.projectId()))throw notFound("PROJECT_NOT_FOUND");
    var existing=jdbc.sql("SELECT id,project_id,task_type,status,created_at,updated_at,result_reference,failure_code,template_version_id,parameters::text,provider_profile_id,model_id FROM tasks WHERE project_id=:project AND idempotency_key=:key AND owner_id=:owner AND deleted_at IS NULL").param("project",request.projectId()).param("key",key).param("owner",user.id()).query((rs,n)->new ExistingTask(view(rs),rs.getObject(9,UUID.class),rs.getString(10),rs.getObject(11,UUID.class),rs.getString(12))).optional();if(existing.isPresent()){var prior=existing.get();if(!sameIdempotentRequest(prior,request))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.CONFLICT,"IDEMPOTENCY_KEY_REUSED");return prior.view();}
    var revision=jdbc.sql("SELECT id FROM project_revisions WHERE project_id=:project ORDER BY ordinal DESC LIMIT 1").param("project",request.projectId()).query(UUID.class).optional().orElseThrow(()->new IllegalArgumentException("project requires an imported revision"));
    if(!templateMatches(request.templateVersionId(),request.type().name(),user))throw notFound("TEMPLATE_VERSION_NOT_FOUND");
    var provider=resolveProvider(user,request.providerProfileId(),request.modelId()); var id=UUID.randomUUID();var now=OffsetDateTime.now();
    jdbc.sql("INSERT INTO tasks(id,project_id,task_type,status,idempotency_key,input_reference,created_at,updated_at,owner_id,project_revision_id,template_version_id,parameters,provider_profile_id,model_id) VALUES(:id,:project,:type,'QUEUED',:key,:input,:now,:now,:owner,:revision,:template,CAST(:parameters AS jsonb),:provider,:model)").param("id",id).param("project",request.projectId()).param("type",request.type().name()).param("key",key).param("input","revision:"+revision).param("now",now).param("owner",user.id()).param("revision",revision).param("template",request.templateVersionId()).param("parameters",json(request.parameters())).param("provider",provider.id()).param("model",provider.model()).update();
    event(id,1,"QUEUED","STATUS",null,"Task queued",null,now);
    workflows.enqueue(id, request.projectId(), request.type(), revision, request.templateVersionId(), provider.id(), false);
    return new View(id,request.projectId(),request.type().name(),"QUEUED",now,now,null,null);
  }
  @GetMapping List<View> list(CurrentUser user){return jdbc.sql("SELECT id,project_id,task_type,status,created_at,updated_at,result_reference,failure_code FROM tasks t WHERE t.deleted_at IS NULL AND (t.owner_id=:owner OR EXISTS(SELECT 1 FROM shares s WHERE s.member_id=:owner AND s.resource_type='PROJECT' AND s.resource_id=t.project_id)) ORDER BY created_at DESC").param("owner",user.id()).query((rs,n)->view(rs)).list();}
  @GetMapping("/{taskId}") View get(CurrentUser user,@PathVariable UUID taskId){return readableTask(user,taskId);}
  @PostMapping("/{taskId}/{action:pause|resume|cancel}") @org.springframework.transaction.annotation.Transactional View action(CurrentUser user,@PathVariable UUID taskId,@PathVariable String action){var current=lockedTask(user,taskId);var next=TaskRules.apply(TaskStatus.valueOf(current.status()),TaskAction.valueOf(action.toUpperCase()));if(next.name().equals(current.status()))return current;var now=OffsetDateTime.now();jdbc.sql("UPDATE tasks SET status=:status,updated_at=:now WHERE id=:id").param("status",next.name()).param("now",now).param("id",taskId).update();event(taskId,nextSequence(taskId),next.name(),"STATUS",null,action,null,now);workflows.enqueueSignal(taskId,action);return new View(current.taskId(),current.projectId(),current.type(),next.name(),current.createdAt(),now,current.resultReference(),current.failureCode());}
  @DeleteMapping("/{taskId}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(CurrentUser user,@PathVariable UUID taskId){var current=task(user,taskId);if(!TaskRules.canDelete(TaskStatus.valueOf(current.status())))throw new IllegalStateException("only terminal tasks can be deleted");jdbc.sql("UPDATE tasks SET deleted_at=:now WHERE id=:id").param("id",taskId).param("now",OffsetDateTime.now()).update();}
  @PostMapping("/batch-delete") @ResponseStatus(HttpStatus.NO_CONTENT) void batchDelete(CurrentUser user,@RequestBody List<UUID> ids){for(var id:ids)delete(user,id);}
  @GetMapping(value="/{taskId}/events",produces="text/event-stream") SseEmitter events(CurrentUser user,@PathVariable UUID taskId,@RequestHeader(value="Last-Event-ID",required=false) Long after){readableTask(user,taskId);var emitter=new SseEmitter(0L);jdbc.sql("SELECT sequence,status,result_reference,failure_code,event_type,progress,message,details::text,occurred_at FROM task_events WHERE task_id=:id AND sequence>:after ORDER BY sequence").param("id",taskId).param("after",after==null?0:after).query((rs,n)->{var value=new java.util.LinkedHashMap<String,Object>();value.put("sequence",rs.getLong(1));value.put("status",rs.getString(2));value.put("resultReference",rs.getString(3));value.put("failureCode",rs.getString(4));value.put("type",rs.getString(5));value.put("progress",rs.getObject(6));value.put("message",rs.getString(7));value.put("details",rs.getString(8));value.put("occurredAt",rs.getObject(9,OffsetDateTime.class));return value;}).list().forEach(value->{try{emitter.send(SseEmitter.event().id(value.get("sequence").toString()).name("task-event").data(value));}catch(Exception e){emitter.completeWithError(e);}});emitter.complete();return emitter;}
  @PostMapping("/{taskId}/approvals") @ResponseStatus(HttpStatus.CREATED) @org.springframework.transaction.annotation.Transactional Map<String,Object> requestApproval(CurrentUser user,@PathVariable UUID taskId,@RequestBody ApprovalInput input){var task=lockedTask(user,taskId);var now=OffsetDateTime.now();ApprovalRules.request(task.status(),input.kind(),input.prompt(),input.choices(),input.expiresAt(),now);var id=UUID.randomUUID();jdbc.sql("INSERT INTO task_approvals(id,task_id,kind,prompt,choices,requested_at,expires_at) VALUES(:id,:task,:kind,:prompt,CAST(:choices AS jsonb),:now,:expires)").param("id",id).param("task",taskId).param("kind",input.kind()).param("prompt",input.prompt()).param("choices",json(input.choices())).param("now",now).param("expires",input.expiresAt()).update();jdbc.sql("UPDATE tasks SET status='WAITING_FOR_APPROVAL',updated_at=:now WHERE id=:id").param("now",now).param("id",taskId).update();event(taskId,nextSequence(taskId),"WAITING_FOR_APPROVAL","APPROVAL",null,"approval requested",null,now);return Map.of("id",id,"status","WAITING_FOR_APPROVAL");}
  @GetMapping("/{taskId}/approvals/pending") Map<String,Object> pendingApproval(CurrentUser user,@PathVariable UUID taskId){task(user,taskId);return jdbc.sql("SELECT id,kind,prompt,choices::text,expires_at,evidence_reference FROM task_approvals WHERE task_id=:task AND decided_at IS NULL AND (expires_at IS NULL OR expires_at>:now) ORDER BY requested_at DESC LIMIT 1").param("task",taskId).param("now",OffsetDateTime.now()).query((rs,n)->{var result=new java.util.LinkedHashMap<String,Object>();result.put("id",rs.getObject(1,UUID.class));result.put("kind",rs.getString(2));result.put("prompt",rs.getString(3));result.put("choices",choices((String)rs.getString(4)));result.put("expiresAt",rs.getObject(5,OffsetDateTime.class));result.put("evidenceReference",rs.getString(6));return result;}).optional().orElseThrow(()->notFound("APPROVAL_NOT_FOUND"));}
  @PostMapping("/{taskId}/approvals/{approvalId}/decision") @ResponseStatus(HttpStatus.NO_CONTENT) @org.springframework.transaction.annotation.Transactional void decide(CurrentUser user,@PathVariable UUID taskId,@PathVariable UUID approvalId,@RequestBody DecisionInput input){var task=lockedTask(user,taskId);if(!"WAITING_FOR_APPROVAL".equals(task.status()))throw new IllegalStateException("task is not waiting for approval");var approval=jdbc.sql("SELECT kind,choices::text,expires_at,evidence_reference FROM task_approvals WHERE id=:id AND task_id=:task AND decided_at IS NULL FOR UPDATE").param("id",approvalId).param("task",taskId).query((rs,n)->new Object[]{rs.getString(1),rs.getString(2),rs.getObject(3,OffsetDateTime.class),rs.getString(4)}).optional().orElseThrow(()->new IllegalStateException("approval is not pending"));var evidence=(String)approval[3];if(evidence!=null&&!evidence.equals(input.approvedReference()))throw new IllegalArgumentException("approval evidence does not match");var now=OffsetDateTime.now();ApprovalRules.decide((String)approval[0],choices((String)approval[1]),input.decision(),input.text(),(OffsetDateTime)approval[2],now);if(jdbc.sql("UPDATE task_approvals SET decision=:decision,response_text=:text,decided_at=:now,decided_by=:user WHERE id=:id").param("decision",input.decision()).param("text",input.text()).param("now",now).param("user",user.id()).param("id",approvalId).update()!=1)throw new IllegalStateException("approval is not pending");boolean rejected=input.decision()!=null&&Set.of("reject","rejected","cancel").contains(input.decision().trim().toLowerCase(java.util.Locale.ROOT));String status=rejected?"CANCELED":"RUNNING";jdbc.sql("UPDATE tasks SET status=:status,updated_at=:now WHERE id=:id").param("status",status).param("now",now).param("id",taskId).update();event(taskId,nextSequence(taskId),status,"APPROVAL",null,rejected?"approval rejected":"approval decided",null,now);if(evidence!=null)workflows.enqueueApproval(taskId,input.decision(),evidence);}
  private View task(CurrentUser user,UUID id){return findTask(user,id,"",true);}
  private View readableTask(CurrentUser user,UUID id){return findTask(user,id,"",false);}
  private View lockedTask(CurrentUser user,UUID id){return findTask(user,id," FOR UPDATE",true);}
  private View findTask(CurrentUser user,UUID id,String lock,boolean ownerOnly){String access=ownerOnly?"owner_id=:owner":"(owner_id=:owner OR EXISTS(SELECT 1 FROM shares s WHERE s.member_id=:owner AND s.resource_type='PROJECT' AND s.resource_id=tasks.project_id))";return jdbc.sql("SELECT id,project_id,task_type,status,created_at,updated_at,result_reference,failure_code FROM tasks WHERE id=:id AND "+access+" AND deleted_at IS NULL"+lock).param("id",id).param("owner",user.id()).query((rs,n)->view(rs)).optional().orElseThrow(()->notFound("TASK_NOT_FOUND"));}
  private boolean ownsProject(CurrentUser user,UUID project){return jdbc.sql("SELECT EXISTS(SELECT 1 FROM projects WHERE id=:id AND owner_id=:owner)").param("id",project).param("owner",user.id()).query(Boolean.class).single();}
  private boolean templateMatches(UUID version,String taskType,CurrentUser user){return jdbc.sql("SELECT EXISTS(SELECT 1 FROM template_versions v JOIN templates t ON t.id=v.template_id JOIN skills s ON s.id=t.skill_id WHERE v.id=:id AND s.task_type=:type AND (t.owner_id=:owner OR t.visibility='PUBLIC'))").param("id",version).param("type",taskType).param("owner",user.id()).query(Boolean.class).single();}
  private ProviderSelection resolveProvider(CurrentUser user,UUID provider,String model){if(provider==null){provider=jdbc.sql("SELECT id FROM provider_profiles WHERE owner_id=:owner AND is_default=true").param("owner",user.id()).query(UUID.class).optional().orElseThrow(()->new IllegalArgumentException("default provider is required"));model=jdbc.sql("SELECT model_id FROM provider_models WHERE provider_profile_id=:id AND is_default=true").param("id",provider).query(String.class).optional().orElseThrow(()->new IllegalArgumentException("default model is required"));}if(!jdbc.sql("SELECT EXISTS(SELECT 1 FROM provider_models m JOIN provider_profiles p ON p.id=m.provider_profile_id WHERE p.id=:provider AND p.owner_id=:owner AND m.model_id=:model)").param("provider",provider).param("owner",user.id()).param("model",model).query(Boolean.class).single())throw new IllegalArgumentException("provider/model selection is invalid");return new ProviderSelection(provider,model);}
  private void event(UUID task,long sequence,String status,String type,Integer progress,String message,String details,OffsetDateTime now){jdbc.sql("INSERT INTO task_events(task_id,sequence,status,event_type,progress,message,details,occurred_at) VALUES(:task,:seq,:status,:type,:progress,:message,CAST(:details AS jsonb),:now)").param("task",task).param("seq",sequence).param("status",status).param("type",type).param("progress",progress).param("message",message).param("details",details==null?"{}":details).param("now",now).update();}
  private long nextSequence(UUID id){return jdbc.sql("SELECT COALESCE(MAX(sequence),0)+1 FROM task_events WHERE task_id=:id").param("id",id).query(Long.class).single();}
  private static View view(java.sql.ResultSet rs)throws java.sql.SQLException{return new View(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3),rs.getString(4),rs.getObject(5,OffsetDateTime.class),rs.getObject(6,OffsetDateTime.class),rs.getString(7),rs.getString(8));}
  private static String normalizeIdempotencyKey(String key){if(key==null||key.isBlank()||key.trim().length()>255)throw new IllegalArgumentException("Idempotency-Key is invalid");return key.trim();}
  private static boolean sameIdempotentRequest(ExistingTask prior,CreateTaskRequest request){if(!prior.view().type().equals(request.type().name())||!prior.templateVersionId().equals(request.templateVersionId())||!sameJson(prior.parameters(),request.parameters()))return false;if(request.providerProfileId()!=null)return request.providerProfileId().equals(prior.providerProfileId())&&request.modelId().equals(prior.modelId());return true;}
  private static boolean sameJson(String stored,Object requested){try{var mapper=new tools.jackson.databind.ObjectMapper();return mapper.readTree(stored).equals(mapper.readTree(mapper.writeValueAsString(requested)));}catch(Exception e){return false;}}
  private static String json(Object v){try{return new tools.jackson.databind.ObjectMapper().writeValueAsString(v==null?Map.of():v);}catch(tools.jackson.core.JacksonException e){throw new IllegalArgumentException("invalid JSON",e);}}
  private static List<String> choices(String value){try{return new tools.jackson.databind.ObjectMapper().readValue(value,List.class);}catch(tools.jackson.core.JacksonException e){throw new IllegalStateException("stored approval choices are invalid",e);}}
  private static org.springframework.web.server.ResponseStatusException notFound(String code){return new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND,code);}
  private record ProviderSelection(UUID id,String model) {}
  private record ExistingTask(View view,UUID templateVersionId,String parameters,UUID providerProfileId,String modelId) {}
}
