package studio.agent.platform.product;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;
import studio.agent.platform.security.CurrentUser;
import studio.agent.platform.security.SecretBox;
import studio.agent.contracts.LoginLocator;

@RestController
@RequestMapping("/api/v1/login-profiles")
public class LoginProfileController {
  private final JdbcClient jdbc; private final SecretBox secrets;
  public LoginProfileController(JdbcClient jdbc, SecretBox secrets){this.jdbc=jdbc;this.secrets=secrets;}
  record Input(String reference,String name,String loginUrl,String loginPath,LoginLocator usernameLocator,LoginLocator passwordLocator,LoginLocator submitLocator,String username,String password) {}
  record UpdateInput(String reference,String name,String loginUrl,String loginPath,LoginLocator usernameLocator,LoginLocator passwordLocator,LoginLocator submitLocator) {}
  record CredentialInput(String username,String password) {}
  record View(UUID id,String reference,String name,String loginUrl,String loginPath,LoginLocator usernameLocator,LoginLocator passwordLocator,LoginLocator submitLocator) {}
  @GetMapping List<View> list(CurrentUser user){return jdbc.sql("SELECT id,reference,name,login_url,login_path,username_locator::text,password_locator::text,submit_locator::text FROM login_profiles WHERE owner_id=:owner ORDER BY created_at DESC").param("owner",user.id()).query((rs,n)->new View(rs.getObject(1,UUID.class),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),locator(rs.getString(6)),locator(rs.getString(7)),locator(rs.getString(8)))).list();}
  @PostMapping @ResponseStatus(HttpStatus.CREATED) View create(CurrentUser user,@RequestBody Input r){if(r.reference()==null||r.name()==null||r.loginUrl()==null||r.usernameLocator()==null||r.passwordLocator()==null||r.submitLocator()==null||r.username()==null||r.password()==null)throw new IllegalArgumentException("login profile fields are required");validateText(r.reference(),"reference",128);validateText(r.name(),"name",255);validateUrl(r.loginUrl());var id=UUID.randomUUID();var now=OffsetDateTime.now();jdbc.sql("INSERT INTO login_profiles(id,owner_id,reference,name,login_url,login_path,username_locator,password_locator,submit_locator,encrypted_username,encrypted_password,created_at,updated_at) VALUES(:id,:owner,:ref,:name,:url,:path,CAST(:userLoc AS jsonb),CAST(:passLoc AS jsonb),CAST(:submit AS jsonb),:user,:pass,:now,:now)").param("id",id).param("owner",user.id()).param("ref",r.reference().trim()).param("name",r.name().trim()).param("url",r.loginUrl().trim()).param("path",r.loginPath()).param("userLoc",json(r.usernameLocator())).param("passLoc",json(r.passwordLocator())).param("submit",json(r.submitLocator())).param("user",secrets.encrypt(user.id().toString(),r.username())).param("pass",secrets.encrypt(user.id().toString(),r.password())).param("now",now).update();return new View(id,r.reference().trim(),r.name().trim(),r.loginUrl().trim(),r.loginPath(),r.usernameLocator(),r.passwordLocator(),r.submitLocator());}
  @PatchMapping("/{profileId}") @org.springframework.transaction.annotation.Transactional View update(CurrentUser user,@PathVariable UUID profileId,@RequestBody UpdateInput r){var current=owned(user,profileId);String reference=r.reference()==null?current.reference():r.reference().trim();String name=r.name()==null?current.name():r.name().trim();String url=r.loginUrl()==null?current.loginUrl():r.loginUrl().trim();String path=r.loginPath()==null?current.loginPath():r.loginPath();LoginLocator userLocator=r.usernameLocator()==null?current.usernameLocator():r.usernameLocator();LoginLocator passLocator=r.passwordLocator()==null?current.passwordLocator():r.passwordLocator();LoginLocator submitLocator=r.submitLocator()==null?current.submitLocator():r.submitLocator();validateText(reference,"reference",128);validateText(name,"name",255);validateUrl(url);var now=OffsetDateTime.now();jdbc.sql("UPDATE login_profiles SET reference=:ref,name=:name,login_url=:url,login_path=:path,username_locator=CAST(:userLoc AS jsonb),password_locator=CAST(:passLoc AS jsonb),submit_locator=CAST(:submit AS jsonb),updated_at=:now WHERE id=:id AND owner_id=:owner").param("ref",reference).param("name",name).param("url",url).param("path",path).param("userLoc",json(userLocator)).param("passLoc",json(passLocator)).param("submitLoc",json(submitLocator)).param("now",now).param("id",profileId).param("owner",user.id()).update();return new View(profileId,reference,name,url,path,userLocator,passLocator,submitLocator);}
  @PostMapping("/{profileId}/credentials/rotate") @org.springframework.transaction.annotation.Transactional void rotate(CurrentUser user,@PathVariable UUID profileId,@RequestBody CredentialInput r){owned(user,profileId);if(r.username()==null||r.password()==null||r.username().isBlank()||r.password().isBlank())throw new IllegalArgumentException("username and password are required");jdbc.sql("UPDATE login_profiles SET encrypted_username=:user,encrypted_password=:pass,updated_at=:now WHERE id=:id AND owner_id=:owner").param("user",secrets.encrypt(user.id().toString(),r.username())).param("pass",secrets.encrypt(user.id().toString(),r.password())).param("now",OffsetDateTime.now()).param("id",profileId).param("owner",user.id()).update();}
  @DeleteMapping("/{profileId}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(CurrentUser user,@PathVariable UUID profileId){owned(user,profileId);jdbc.sql("DELETE FROM login_profiles WHERE id=:id AND owner_id=:owner").param("id",profileId).param("owner",user.id()).update();}
  private static String json(LoginLocator locator){try{return new tools.jackson.databind.ObjectMapper().writeValueAsString(locator);}catch(tools.jackson.core.JacksonException e){throw new IllegalArgumentException("locator is invalid",e);}}
  private static LoginLocator locator(String json){try{return new tools.jackson.databind.ObjectMapper().readValue(json,LoginLocator.class);}catch(tools.jackson.core.JacksonException e){throw new IllegalStateException("stored locator is invalid",e);}}
  private Owned owned(CurrentUser user,UUID id){return jdbc.sql("SELECT reference,name,login_url,login_path,username_locator::text,password_locator::text,submit_locator::text FROM login_profiles WHERE id=:id AND owner_id=:owner").param("id",id).param("owner",user.id()).query((rs,n)->new Owned(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),locator(rs.getString(5)),locator(rs.getString(6)),locator(rs.getString(7)))).optional().orElseThrow(()->new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND,"LOGIN_PROFILE_NOT_FOUND"));}
  private static void validateText(String value,String field,int max){if(value==null||value.isBlank()||value.trim().length()>max)throw new IllegalArgumentException(field+" is invalid");}
  private static void validateUrl(String value){try{var uri=java.net.URI.create(value==null?"":value.trim());if(!("http".equalsIgnoreCase(uri.getScheme())||"https".equalsIgnoreCase(uri.getScheme()))||uri.getHost()==null||uri.getUserInfo()!=null||uri.getFragment()!=null)throw new IllegalArgumentException("loginUrl is invalid");}catch(Exception e){if(e instanceof IllegalArgumentException a&&"loginUrl is invalid".equals(a.getMessage()))throw a;throw new IllegalArgumentException("loginUrl is invalid");}}
  private record Owned(String reference,String name,String loginUrl,String loginPath,LoginLocator usernameLocator,LoginLocator passwordLocator,LoginLocator submitLocator){}
}
