services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"
  minio:
    ports:
      - "127.0.0.1:9000:9000"
  mailpit:
    ports:
      - "127.0.0.1:1025:1025"
  temporal-postgres:
    ports:
      - "127.0.0.1:5433:5432"
